[tool.black]
line-length = 120
include = '\.pyi?$'
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tests
)/
'''